'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSRestaurante
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSRestaurante.RestauranteSoap")>  _
    Public Interface RestauranteSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descripcion_pedido del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RecibirPedidoCliente", ReplyAction:="*")>  _
        Function RecibirPedidoCliente(ByVal request As WSRestaurante.RecibirPedidoClienteRequest) As WSRestaurante.RecibirPedidoClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RecibirPedidoCliente", ReplyAction:="*")>  _
        Function RecibirPedidoClienteAsync(ByVal request As WSRestaurante.RecibirPedidoClienteRequest) As System.Threading.Tasks.Task(Of WSRestaurante.RecibirPedidoClienteResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EstadoPedidoClienteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoCliente", ReplyAction:="*")>  _
        Function EstadoPedidoCliente(ByVal request As WSRestaurante.EstadoPedidoClienteRequest) As WSRestaurante.EstadoPedidoClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoCliente", ReplyAction:="*")>  _
        Function EstadoPedidoClienteAsync(ByVal request As WSRestaurante.EstadoPedidoClienteRequest) As System.Threading.Tasks.Task(Of WSRestaurante.EstadoPedidoClienteResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre_repartidor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PedidoListoRepartidor", ReplyAction:="*")>  _
        Function PedidoListoRepartidor(ByVal request As WSRestaurante.PedidoListoRepartidorRequest) As WSRestaurante.PedidoListoRepartidorResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PedidoListoRepartidor", ReplyAction:="*")>  _
        Function PedidoListoRepartidorAsync(ByVal request As WSRestaurante.PedidoListoRepartidorRequest) As System.Threading.Tasks.Task(Of WSRestaurante.PedidoListoRepartidorResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibirPedidoClienteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecibirPedidoCliente", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRestaurante.RecibirPedidoClienteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRestaurante.RecibirPedidoClienteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RecibirPedidoClienteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public descripcion_pedido As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal descripcion_pedido As String)
            MyBase.New
            Me.descripcion_pedido = descripcion_pedido
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibirPedidoClienteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecibirPedidoClienteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRestaurante.RecibirPedidoClienteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRestaurante.RecibirPedidoClienteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RecibirPedidoClienteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RecibirPedidoClienteResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RecibirPedidoClienteResult As String)
            MyBase.New
            Me.RecibirPedidoClienteResult = RecibirPedidoClienteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoClienteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoCliente", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRestaurante.EstadoPedidoClienteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRestaurante.EstadoPedidoClienteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoClienteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idpedido As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idpedido As Integer)
            MyBase.New
            Me.idpedido = idpedido
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoClienteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoClienteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRestaurante.EstadoPedidoClienteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRestaurante.EstadoPedidoClienteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoClienteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EstadoPedidoClienteResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EstadoPedidoClienteResult As String)
            MyBase.New
            Me.EstadoPedidoClienteResult = EstadoPedidoClienteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidoListoRepartidorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidoListoRepartidor", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRestaurante.PedidoListoRepartidorRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRestaurante.PedidoListoRepartidorRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PedidoListoRepartidorRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idpedido As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public nombre_repartidor As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idpedido As Integer, ByVal nombre_repartidor As String)
            MyBase.New
            Me.idpedido = idpedido
            Me.nombre_repartidor = nombre_repartidor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidoListoRepartidorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidoListoRepartidorResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRestaurante.PedidoListoRepartidorResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRestaurante.PedidoListoRepartidorResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PedidoListoRepartidorResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public PedidoListoRepartidorResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PedidoListoRepartidorResult As String)
            MyBase.New
            Me.PedidoListoRepartidorResult = PedidoListoRepartidorResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface RestauranteSoapChannel
        Inherits WSRestaurante.RestauranteSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RestauranteSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSRestaurante.RestauranteSoap)
        Implements WSRestaurante.RestauranteSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRestaurante_RestauranteSoap_RecibirPedidoCliente(ByVal request As WSRestaurante.RecibirPedidoClienteRequest) As WSRestaurante.RecibirPedidoClienteResponse Implements WSRestaurante.RestauranteSoap.RecibirPedidoCliente
            Return MyBase.Channel.RecibirPedidoCliente(request)
        End Function
        
        Public Function RecibirPedidoCliente(ByVal descripcion_pedido As String) As String
            Dim inValue As WSRestaurante.RecibirPedidoClienteRequest = New WSRestaurante.RecibirPedidoClienteRequest()
            inValue.Body = New WSRestaurante.RecibirPedidoClienteRequestBody()
            inValue.Body.descripcion_pedido = descripcion_pedido
            Dim retVal As WSRestaurante.RecibirPedidoClienteResponse = CType(Me,WSRestaurante.RestauranteSoap).RecibirPedidoCliente(inValue)
            Return retVal.Body.RecibirPedidoClienteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRestaurante_RestauranteSoap_RecibirPedidoClienteAsync(ByVal request As WSRestaurante.RecibirPedidoClienteRequest) As System.Threading.Tasks.Task(Of WSRestaurante.RecibirPedidoClienteResponse) Implements WSRestaurante.RestauranteSoap.RecibirPedidoClienteAsync
            Return MyBase.Channel.RecibirPedidoClienteAsync(request)
        End Function
        
        Public Function RecibirPedidoClienteAsync(ByVal descripcion_pedido As String) As System.Threading.Tasks.Task(Of WSRestaurante.RecibirPedidoClienteResponse)
            Dim inValue As WSRestaurante.RecibirPedidoClienteRequest = New WSRestaurante.RecibirPedidoClienteRequest()
            inValue.Body = New WSRestaurante.RecibirPedidoClienteRequestBody()
            inValue.Body.descripcion_pedido = descripcion_pedido
            Return CType(Me,WSRestaurante.RestauranteSoap).RecibirPedidoClienteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRestaurante_RestauranteSoap_EstadoPedidoCliente(ByVal request As WSRestaurante.EstadoPedidoClienteRequest) As WSRestaurante.EstadoPedidoClienteResponse Implements WSRestaurante.RestauranteSoap.EstadoPedidoCliente
            Return MyBase.Channel.EstadoPedidoCliente(request)
        End Function
        
        Public Function EstadoPedidoCliente(ByVal idpedido As Integer) As String
            Dim inValue As WSRestaurante.EstadoPedidoClienteRequest = New WSRestaurante.EstadoPedidoClienteRequest()
            inValue.Body = New WSRestaurante.EstadoPedidoClienteRequestBody()
            inValue.Body.idpedido = idpedido
            Dim retVal As WSRestaurante.EstadoPedidoClienteResponse = CType(Me,WSRestaurante.RestauranteSoap).EstadoPedidoCliente(inValue)
            Return retVal.Body.EstadoPedidoClienteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRestaurante_RestauranteSoap_EstadoPedidoClienteAsync(ByVal request As WSRestaurante.EstadoPedidoClienteRequest) As System.Threading.Tasks.Task(Of WSRestaurante.EstadoPedidoClienteResponse) Implements WSRestaurante.RestauranteSoap.EstadoPedidoClienteAsync
            Return MyBase.Channel.EstadoPedidoClienteAsync(request)
        End Function
        
        Public Function EstadoPedidoClienteAsync(ByVal idpedido As Integer) As System.Threading.Tasks.Task(Of WSRestaurante.EstadoPedidoClienteResponse)
            Dim inValue As WSRestaurante.EstadoPedidoClienteRequest = New WSRestaurante.EstadoPedidoClienteRequest()
            inValue.Body = New WSRestaurante.EstadoPedidoClienteRequestBody()
            inValue.Body.idpedido = idpedido
            Return CType(Me,WSRestaurante.RestauranteSoap).EstadoPedidoClienteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRestaurante_RestauranteSoap_PedidoListoRepartidor(ByVal request As WSRestaurante.PedidoListoRepartidorRequest) As WSRestaurante.PedidoListoRepartidorResponse Implements WSRestaurante.RestauranteSoap.PedidoListoRepartidor
            Return MyBase.Channel.PedidoListoRepartidor(request)
        End Function
        
        Public Function PedidoListoRepartidor(ByVal idpedido As Integer, ByVal nombre_repartidor As String) As String
            Dim inValue As WSRestaurante.PedidoListoRepartidorRequest = New WSRestaurante.PedidoListoRepartidorRequest()
            inValue.Body = New WSRestaurante.PedidoListoRepartidorRequestBody()
            inValue.Body.idpedido = idpedido
            inValue.Body.nombre_repartidor = nombre_repartidor
            Dim retVal As WSRestaurante.PedidoListoRepartidorResponse = CType(Me,WSRestaurante.RestauranteSoap).PedidoListoRepartidor(inValue)
            Return retVal.Body.PedidoListoRepartidorResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRestaurante_RestauranteSoap_PedidoListoRepartidorAsync(ByVal request As WSRestaurante.PedidoListoRepartidorRequest) As System.Threading.Tasks.Task(Of WSRestaurante.PedidoListoRepartidorResponse) Implements WSRestaurante.RestauranteSoap.PedidoListoRepartidorAsync
            Return MyBase.Channel.PedidoListoRepartidorAsync(request)
        End Function
        
        Public Function PedidoListoRepartidorAsync(ByVal idpedido As Integer, ByVal nombre_repartidor As String) As System.Threading.Tasks.Task(Of WSRestaurante.PedidoListoRepartidorResponse)
            Dim inValue As WSRestaurante.PedidoListoRepartidorRequest = New WSRestaurante.PedidoListoRepartidorRequest()
            inValue.Body = New WSRestaurante.PedidoListoRepartidorRequestBody()
            inValue.Body.idpedido = idpedido
            inValue.Body.nombre_repartidor = nombre_repartidor
            Return CType(Me,WSRestaurante.RestauranteSoap).PedidoListoRepartidorAsync(inValue)
        End Function
    End Class
End Namespace
