version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql4
    environment:
      MYSQL_DATABASE: datos
      MYSQL_USER: root
      MYSQL_PASSWORD: 451432
      MYSQL_ROOT_PASSWORD: 451432
    volumes:
      - vol-mysql:volx
    ports:
      - "3306:3306"
    restart: always
    
  web:
    image: php:7.3-apache
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
      
      
volumes:
    vol-mysql:
        name: volumen # Real ending name
        external: false