'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSRepartidor
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSRepartidor.RepartidorSoap")>  _
    Public Interface RepartidorSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre_repartidor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RecibirEntregaRestaurante", ReplyAction:="*")>  _
        Function RecibirEntregaRestaurante(ByVal request As WSRepartidor.RecibirEntregaRestauranteRequest) As WSRepartidor.RecibirEntregaRestauranteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RecibirEntregaRestaurante", ReplyAction:="*")>  _
        Function RecibirEntregaRestauranteAsync(ByVal request As WSRepartidor.RecibirEntregaRestauranteRequest) As System.Threading.Tasks.Task(Of WSRepartidor.RecibirEntregaRestauranteResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EstadoPedidoClienteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoCliente", ReplyAction:="*")>  _
        Function EstadoPedidoCliente(ByVal request As WSRepartidor.EstadoPedidoClienteRequest) As WSRepartidor.EstadoPedidoClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoCliente", ReplyAction:="*")>  _
        Function EstadoPedidoClienteAsync(ByVal request As WSRepartidor.EstadoPedidoClienteRequest) As System.Threading.Tasks.Task(Of WSRepartidor.EstadoPedidoClienteResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PedidoEntregadoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PedidoEntregado", ReplyAction:="*")>  _
        Function PedidoEntregado(ByVal request As WSRepartidor.PedidoEntregadoRequest) As WSRepartidor.PedidoEntregadoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PedidoEntregado", ReplyAction:="*")>  _
        Function PedidoEntregadoAsync(ByVal request As WSRepartidor.PedidoEntregadoRequest) As System.Threading.Tasks.Task(Of WSRepartidor.PedidoEntregadoResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibirEntregaRestauranteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecibirEntregaRestaurante", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRepartidor.RecibirEntregaRestauranteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRepartidor.RecibirEntregaRestauranteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RecibirEntregaRestauranteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idPedido As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public nombre_repartidor As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idPedido As Integer, ByVal nombre_repartidor As String)
            MyBase.New
            Me.idPedido = idPedido
            Me.nombre_repartidor = nombre_repartidor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibirEntregaRestauranteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecibirEntregaRestauranteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRepartidor.RecibirEntregaRestauranteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRepartidor.RecibirEntregaRestauranteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RecibirEntregaRestauranteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RecibirEntregaRestauranteResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RecibirEntregaRestauranteResult As String)
            MyBase.New
            Me.RecibirEntregaRestauranteResult = RecibirEntregaRestauranteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoClienteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoCliente", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRepartidor.EstadoPedidoClienteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRepartidor.EstadoPedidoClienteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoClienteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idpedido As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idpedido As Integer)
            MyBase.New
            Me.idpedido = idpedido
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoClienteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoClienteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRepartidor.EstadoPedidoClienteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRepartidor.EstadoPedidoClienteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoClienteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EstadoPedidoClienteResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EstadoPedidoClienteResult As String)
            MyBase.New
            Me.EstadoPedidoClienteResult = EstadoPedidoClienteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidoEntregadoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidoEntregado", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRepartidor.PedidoEntregadoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRepartidor.PedidoEntregadoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PedidoEntregadoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idpedido As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idpedido As Integer)
            MyBase.New
            Me.idpedido = idpedido
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidoEntregadoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidoEntregadoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRepartidor.PedidoEntregadoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRepartidor.PedidoEntregadoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PedidoEntregadoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public PedidoEntregadoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PedidoEntregadoResult As String)
            MyBase.New
            Me.PedidoEntregadoResult = PedidoEntregadoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface RepartidorSoapChannel
        Inherits WSRepartidor.RepartidorSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RepartidorSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSRepartidor.RepartidorSoap)
        Implements WSRepartidor.RepartidorSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRepartidor_RepartidorSoap_RecibirEntregaRestaurante(ByVal request As WSRepartidor.RecibirEntregaRestauranteRequest) As WSRepartidor.RecibirEntregaRestauranteResponse Implements WSRepartidor.RepartidorSoap.RecibirEntregaRestaurante
            Return MyBase.Channel.RecibirEntregaRestaurante(request)
        End Function
        
        Public Function RecibirEntregaRestaurante(ByVal idPedido As Integer, ByVal nombre_repartidor As String) As String
            Dim inValue As WSRepartidor.RecibirEntregaRestauranteRequest = New WSRepartidor.RecibirEntregaRestauranteRequest()
            inValue.Body = New WSRepartidor.RecibirEntregaRestauranteRequestBody()
            inValue.Body.idPedido = idPedido
            inValue.Body.nombre_repartidor = nombre_repartidor
            Dim retVal As WSRepartidor.RecibirEntregaRestauranteResponse = CType(Me,WSRepartidor.RepartidorSoap).RecibirEntregaRestaurante(inValue)
            Return retVal.Body.RecibirEntregaRestauranteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRepartidor_RepartidorSoap_RecibirEntregaRestauranteAsync(ByVal request As WSRepartidor.RecibirEntregaRestauranteRequest) As System.Threading.Tasks.Task(Of WSRepartidor.RecibirEntregaRestauranteResponse) Implements WSRepartidor.RepartidorSoap.RecibirEntregaRestauranteAsync
            Return MyBase.Channel.RecibirEntregaRestauranteAsync(request)
        End Function
        
        Public Function RecibirEntregaRestauranteAsync(ByVal idPedido As Integer, ByVal nombre_repartidor As String) As System.Threading.Tasks.Task(Of WSRepartidor.RecibirEntregaRestauranteResponse)
            Dim inValue As WSRepartidor.RecibirEntregaRestauranteRequest = New WSRepartidor.RecibirEntregaRestauranteRequest()
            inValue.Body = New WSRepartidor.RecibirEntregaRestauranteRequestBody()
            inValue.Body.idPedido = idPedido
            inValue.Body.nombre_repartidor = nombre_repartidor
            Return CType(Me,WSRepartidor.RepartidorSoap).RecibirEntregaRestauranteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRepartidor_RepartidorSoap_EstadoPedidoCliente(ByVal request As WSRepartidor.EstadoPedidoClienteRequest) As WSRepartidor.EstadoPedidoClienteResponse Implements WSRepartidor.RepartidorSoap.EstadoPedidoCliente
            Return MyBase.Channel.EstadoPedidoCliente(request)
        End Function
        
        Public Function EstadoPedidoCliente(ByVal idpedido As Integer) As String
            Dim inValue As WSRepartidor.EstadoPedidoClienteRequest = New WSRepartidor.EstadoPedidoClienteRequest()
            inValue.Body = New WSRepartidor.EstadoPedidoClienteRequestBody()
            inValue.Body.idpedido = idpedido
            Dim retVal As WSRepartidor.EstadoPedidoClienteResponse = CType(Me,WSRepartidor.RepartidorSoap).EstadoPedidoCliente(inValue)
            Return retVal.Body.EstadoPedidoClienteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRepartidor_RepartidorSoap_EstadoPedidoClienteAsync(ByVal request As WSRepartidor.EstadoPedidoClienteRequest) As System.Threading.Tasks.Task(Of WSRepartidor.EstadoPedidoClienteResponse) Implements WSRepartidor.RepartidorSoap.EstadoPedidoClienteAsync
            Return MyBase.Channel.EstadoPedidoClienteAsync(request)
        End Function
        
        Public Function EstadoPedidoClienteAsync(ByVal idpedido As Integer) As System.Threading.Tasks.Task(Of WSRepartidor.EstadoPedidoClienteResponse)
            Dim inValue As WSRepartidor.EstadoPedidoClienteRequest = New WSRepartidor.EstadoPedidoClienteRequest()
            inValue.Body = New WSRepartidor.EstadoPedidoClienteRequestBody()
            inValue.Body.idpedido = idpedido
            Return CType(Me,WSRepartidor.RepartidorSoap).EstadoPedidoClienteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRepartidor_RepartidorSoap_PedidoEntregado(ByVal request As WSRepartidor.PedidoEntregadoRequest) As WSRepartidor.PedidoEntregadoResponse Implements WSRepartidor.RepartidorSoap.PedidoEntregado
            Return MyBase.Channel.PedidoEntregado(request)
        End Function
        
        Public Function PedidoEntregado(ByVal idpedido As Integer) As String
            Dim inValue As WSRepartidor.PedidoEntregadoRequest = New WSRepartidor.PedidoEntregadoRequest()
            inValue.Body = New WSRepartidor.PedidoEntregadoRequestBody()
            inValue.Body.idpedido = idpedido
            Dim retVal As WSRepartidor.PedidoEntregadoResponse = CType(Me,WSRepartidor.RepartidorSoap).PedidoEntregado(inValue)
            Return retVal.Body.PedidoEntregadoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRepartidor_RepartidorSoap_PedidoEntregadoAsync(ByVal request As WSRepartidor.PedidoEntregadoRequest) As System.Threading.Tasks.Task(Of WSRepartidor.PedidoEntregadoResponse) Implements WSRepartidor.RepartidorSoap.PedidoEntregadoAsync
            Return MyBase.Channel.PedidoEntregadoAsync(request)
        End Function
        
        Public Function PedidoEntregadoAsync(ByVal idpedido As Integer) As System.Threading.Tasks.Task(Of WSRepartidor.PedidoEntregadoResponse)
            Dim inValue As WSRepartidor.PedidoEntregadoRequest = New WSRepartidor.PedidoEntregadoRequest()
            inValue.Body = New WSRepartidor.PedidoEntregadoRequestBody()
            inValue.Body.idpedido = idpedido
            Return CType(Me,WSRepartidor.RepartidorSoap).PedidoEntregadoAsync(inValue)
        End Function
    End Class
End Namespace
