'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSCliente
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSCliente.ClienteSoap")>  _
    Public Interface ClienteSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descripcion_pedido del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HacerPedidoRestaurante", ReplyAction:="*")>  _
        Function HacerPedidoRestaurante(ByVal request As WSCliente.HacerPedidoRestauranteRequest) As WSCliente.HacerPedidoRestauranteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HacerPedidoRestaurante", ReplyAction:="*")>  _
        Function HacerPedidoRestauranteAsync(ByVal request As WSCliente.HacerPedidoRestauranteRequest) As System.Threading.Tasks.Task(Of WSCliente.HacerPedidoRestauranteResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EstadoPedidoRestauranteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoRestaurante", ReplyAction:="*")>  _
        Function EstadoPedidoRestaurante(ByVal request As WSCliente.EstadoPedidoRestauranteRequest) As WSCliente.EstadoPedidoRestauranteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoRestaurante", ReplyAction:="*")>  _
        Function EstadoPedidoRestauranteAsync(ByVal request As WSCliente.EstadoPedidoRestauranteRequest) As System.Threading.Tasks.Task(Of WSCliente.EstadoPedidoRestauranteResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EstadoPedidoRepartidorResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoRepartidor", ReplyAction:="*")>  _
        Function EstadoPedidoRepartidor(ByVal request As WSCliente.EstadoPedidoRepartidorRequest) As WSCliente.EstadoPedidoRepartidorResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoRepartidor", ReplyAction:="*")>  _
        Function EstadoPedidoRepartidorAsync(ByVal request As WSCliente.EstadoPedidoRepartidorRequest) As System.Threading.Tasks.Task(Of WSCliente.EstadoPedidoRepartidorResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HacerPedidoRestauranteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HacerPedidoRestaurante", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCliente.HacerPedidoRestauranteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCliente.HacerPedidoRestauranteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HacerPedidoRestauranteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public descripcion_pedido As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal descripcion_pedido As String)
            MyBase.New
            Me.descripcion_pedido = descripcion_pedido
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HacerPedidoRestauranteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HacerPedidoRestauranteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCliente.HacerPedidoRestauranteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCliente.HacerPedidoRestauranteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HacerPedidoRestauranteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HacerPedidoRestauranteResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HacerPedidoRestauranteResult As String)
            MyBase.New
            Me.HacerPedidoRestauranteResult = HacerPedidoRestauranteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoRestauranteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoRestaurante", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCliente.EstadoPedidoRestauranteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCliente.EstadoPedidoRestauranteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoRestauranteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idpedido As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idpedido As Integer)
            MyBase.New
            Me.idpedido = idpedido
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoRestauranteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoRestauranteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCliente.EstadoPedidoRestauranteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCliente.EstadoPedidoRestauranteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoRestauranteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EstadoPedidoRestauranteResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EstadoPedidoRestauranteResult As String)
            MyBase.New
            Me.EstadoPedidoRestauranteResult = EstadoPedidoRestauranteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoRepartidorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoRepartidor", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCliente.EstadoPedidoRepartidorRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCliente.EstadoPedidoRepartidorRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoRepartidorRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idpedido As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idpedido As Integer)
            MyBase.New
            Me.idpedido = idpedido
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoRepartidorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoRepartidorResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCliente.EstadoPedidoRepartidorResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCliente.EstadoPedidoRepartidorResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoRepartidorResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EstadoPedidoRepartidorResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EstadoPedidoRepartidorResult As String)
            MyBase.New
            Me.EstadoPedidoRepartidorResult = EstadoPedidoRepartidorResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ClienteSoapChannel
        Inherits WSCliente.ClienteSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClienteSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSCliente.ClienteSoap)
        Implements WSCliente.ClienteSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCliente_ClienteSoap_HacerPedidoRestaurante(ByVal request As WSCliente.HacerPedidoRestauranteRequest) As WSCliente.HacerPedidoRestauranteResponse Implements WSCliente.ClienteSoap.HacerPedidoRestaurante
            Return MyBase.Channel.HacerPedidoRestaurante(request)
        End Function
        
        Public Function HacerPedidoRestaurante(ByVal descripcion_pedido As String) As String
            Dim inValue As WSCliente.HacerPedidoRestauranteRequest = New WSCliente.HacerPedidoRestauranteRequest()
            inValue.Body = New WSCliente.HacerPedidoRestauranteRequestBody()
            inValue.Body.descripcion_pedido = descripcion_pedido
            Dim retVal As WSCliente.HacerPedidoRestauranteResponse = CType(Me,WSCliente.ClienteSoap).HacerPedidoRestaurante(inValue)
            Return retVal.Body.HacerPedidoRestauranteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCliente_ClienteSoap_HacerPedidoRestauranteAsync(ByVal request As WSCliente.HacerPedidoRestauranteRequest) As System.Threading.Tasks.Task(Of WSCliente.HacerPedidoRestauranteResponse) Implements WSCliente.ClienteSoap.HacerPedidoRestauranteAsync
            Return MyBase.Channel.HacerPedidoRestauranteAsync(request)
        End Function
        
        Public Function HacerPedidoRestauranteAsync(ByVal descripcion_pedido As String) As System.Threading.Tasks.Task(Of WSCliente.HacerPedidoRestauranteResponse)
            Dim inValue As WSCliente.HacerPedidoRestauranteRequest = New WSCliente.HacerPedidoRestauranteRequest()
            inValue.Body = New WSCliente.HacerPedidoRestauranteRequestBody()
            inValue.Body.descripcion_pedido = descripcion_pedido
            Return CType(Me,WSCliente.ClienteSoap).HacerPedidoRestauranteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCliente_ClienteSoap_EstadoPedidoRestaurante(ByVal request As WSCliente.EstadoPedidoRestauranteRequest) As WSCliente.EstadoPedidoRestauranteResponse Implements WSCliente.ClienteSoap.EstadoPedidoRestaurante
            Return MyBase.Channel.EstadoPedidoRestaurante(request)
        End Function
        
        Public Function EstadoPedidoRestaurante(ByVal idpedido As Integer) As String
            Dim inValue As WSCliente.EstadoPedidoRestauranteRequest = New WSCliente.EstadoPedidoRestauranteRequest()
            inValue.Body = New WSCliente.EstadoPedidoRestauranteRequestBody()
            inValue.Body.idpedido = idpedido
            Dim retVal As WSCliente.EstadoPedidoRestauranteResponse = CType(Me,WSCliente.ClienteSoap).EstadoPedidoRestaurante(inValue)
            Return retVal.Body.EstadoPedidoRestauranteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCliente_ClienteSoap_EstadoPedidoRestauranteAsync(ByVal request As WSCliente.EstadoPedidoRestauranteRequest) As System.Threading.Tasks.Task(Of WSCliente.EstadoPedidoRestauranteResponse) Implements WSCliente.ClienteSoap.EstadoPedidoRestauranteAsync
            Return MyBase.Channel.EstadoPedidoRestauranteAsync(request)
        End Function
        
        Public Function EstadoPedidoRestauranteAsync(ByVal idpedido As Integer) As System.Threading.Tasks.Task(Of WSCliente.EstadoPedidoRestauranteResponse)
            Dim inValue As WSCliente.EstadoPedidoRestauranteRequest = New WSCliente.EstadoPedidoRestauranteRequest()
            inValue.Body = New WSCliente.EstadoPedidoRestauranteRequestBody()
            inValue.Body.idpedido = idpedido
            Return CType(Me,WSCliente.ClienteSoap).EstadoPedidoRestauranteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCliente_ClienteSoap_EstadoPedidoRepartidor(ByVal request As WSCliente.EstadoPedidoRepartidorRequest) As WSCliente.EstadoPedidoRepartidorResponse Implements WSCliente.ClienteSoap.EstadoPedidoRepartidor
            Return MyBase.Channel.EstadoPedidoRepartidor(request)
        End Function
        
        Public Function EstadoPedidoRepartidor(ByVal idpedido As Integer) As String
            Dim inValue As WSCliente.EstadoPedidoRepartidorRequest = New WSCliente.EstadoPedidoRepartidorRequest()
            inValue.Body = New WSCliente.EstadoPedidoRepartidorRequestBody()
            inValue.Body.idpedido = idpedido
            Dim retVal As WSCliente.EstadoPedidoRepartidorResponse = CType(Me,WSCliente.ClienteSoap).EstadoPedidoRepartidor(inValue)
            Return retVal.Body.EstadoPedidoRepartidorResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCliente_ClienteSoap_EstadoPedidoRepartidorAsync(ByVal request As WSCliente.EstadoPedidoRepartidorRequest) As System.Threading.Tasks.Task(Of WSCliente.EstadoPedidoRepartidorResponse) Implements WSCliente.ClienteSoap.EstadoPedidoRepartidorAsync
            Return MyBase.Channel.EstadoPedidoRepartidorAsync(request)
        End Function
        
        Public Function EstadoPedidoRepartidorAsync(ByVal idpedido As Integer) As System.Threading.Tasks.Task(Of WSCliente.EstadoPedidoRepartidorResponse)
            Dim inValue As WSCliente.EstadoPedidoRepartidorRequest = New WSCliente.EstadoPedidoRepartidorRequest()
            inValue.Body = New WSCliente.EstadoPedidoRepartidorRequestBody()
            inValue.Body.idpedido = idpedido
            Return CType(Me,WSCliente.ClienteSoap).EstadoPedidoRepartidorAsync(inValue)
        End Function
    End Class
End Namespace
